### ISSUE TITLE
point in using this over forge

### ISSUE THREAD

**Issue by couleurm** [tildejustin/optifabric#1]
what are the advantages of using fabric in 1.7.10 with optifine over using forge / the installer's version directly?

**Comment by tildejustin** [comment]
Compatibility with legacy fabric mods & legality for speedrunning, I guess? Obviously you could use forge but I personally don't like it so I ported this.

**Comment by couleurm** [comment]
where can i find a list of legacy fabric mods.. never knew it ran on such old versions

**Comment by tildejustin** [comment]
https://legacyfabric.net/mods.html there's not much unfortunately

**Comment by couleurm** [comment]
> [legacyfabric.net/mods.html](https://legacyfabric.net/mods.html) there's not much unfortunately

down to me, do you have an archive / screenshot?

**Comment by tildejustin** [comment]
it's back up now

**Comment by tildejustin** [comment]
this issue is kinda a "sell me on this" when the people using the mod probably already know why they are and are using it out of necessity, so i'm just going to close it
